import { useEffect,useRef,useState } from "react";
import { Cloud,CloudOff,History,LogOut,RefreshCw,ShieldCheck,UserPlus } from "lucide-react";
import type { Session } from "@supabase/supabase-js";
import { GButton,Tag } from "../ui/primitives";import { useStore } from "../../lib/store";import { cloudConfigured,getSupabase } from "../../lib/account/supabase";
import { SyncCoordinator } from "../../lib/sync/syncCoordinator";import { SupabaseSyncTransport } from "../../lib/sync/supabaseTransport";import { clearAccountSync,read,write } from "../../lib/sync/syncMetadata";import type { ProtectedRevision,ProtectionStatus } from "../../lib/sync/syncTypes";import { createLocalBackup } from "../../lib/localBackup";import { parseImport } from "../../lib/backup";

export function AccountSyncPanel(){
 const configured=cloudConfigured();const client=getSupabase();const[session,setSession]=useState<Session|null>(null);const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[message,setMessage]=useState(configured?"Continue locally or sign in when ready.":"Cloud configuration is not installed. AXOM remains fully local.");const[status,setStatus]=useState<ProtectionStatus>(configured?"local-only":"local-only");const[history,setHistory]=useState<ProtectedRevision[]>([]);const[linked,setLinked]=useState(false);const coordinator=useRef<SyncCoordinator>();
 useEffect(()=>{if(!client)return;void client.auth.getSession().then(({data})=>setSession(data.session));const{data}=client.auth.onAuthStateChange((_e,next)=>setSession(next));return()=>data.subscription.unsubscribe();},[client]);
 useEffect(()=>{setLinked(Boolean(session&&read().accountUserId===session.user.id));},[session]);
 useEffect(()=>{if(!session||!linked)return;const c=new SyncCoordinator(new SupabaseSyncTransport(),()=>useStore.getState());coordinator.current=c;const offStatus=c.subscribe(setStatus);const offStore=useStore.subscribe(()=>c.queue());window.addEventListener("online",c.reconnect);if(read().pending)c.reconnect();return()=>{offStatus();offStore();window.removeEventListener("online",c.reconnect);c.dispose();coordinator.current=undefined;};},[session,linked]);
 async function auth(mode:"signUp"|"signIn"){if(!client)return;setMessage("Checking account…");const result=mode==="signUp"?await client.auth.signUp({email,password,options:{data:{display_name:useStore.getState().profile.name}}}):await client.auth.signInWithPassword({email,password});if(result.error){setMessage(`Account unavailable: ${result.error.message}. Your work is still saved locally.`);return;}setMessage(mode==="signUp"&&!result.data.session?"Check your email to confirm the account. Local work is unchanged.":"Account authenticated. Choose how to associate this device; nothing has been replaced.");}
 async function linkLocalWorkspace(){if(!session)return;setMessage("Protecting this device’s existing workspace as the account foundation…");const c=new SyncCoordinator(new SupabaseSyncTransport(),()=>useStore.getState(),0);coordinator.current=c;c.queue();await c.flush("foundation");const syncStatus=c.currentStatus();write({...read(),accountUserId:session.user.id});setLinked(true);setStatus(syncStatus);setMessage(syncStatus==="conflict"?"This device and the account both contain work. Both versions were preserved; choose a protected version or keep this device for review.":syncStatus==="retrying"?"AXOM could not reach the account, but your work is saved on this device. It will retry.":"This workspace is now protected. Future changes sync in the background.");await refresh();}
 async function refresh(){try{setHistory(await new SupabaseSyncTransport().history());}catch(error){setMessage(safeError(error));}}
 async function restore(item:ProtectedRevision){if(!confirm("Replace this device workspace with the selected protected version? AXOM will first create a local safety snapshot, then record the restore as a new server revision."))return;try{parseImport(JSON.stringify(item.payload));await createLocalBackup(useStore.getState().schemaVersion);useStore.getState().replaceAll(parseImport(JSON.stringify(item.payload)));setLinked(true);const c=coordinator.current??new SyncCoordinator(new SupabaseSyncTransport(),()=>useStore.getState(),0);c.queue();await c.flush("restore");const restoreStatus=c.currentStatus();setStatus(restoreStatus);setMessage(restoreStatus==="protected"?"Protected version restored locally and recorded as a new revision.":restoreStatus==="conflict"?"Protected version restored locally. The server retained the upload as a conflict for review instead of replacing the current account version.":"Protected version restored locally. Server protection is still pending and AXOM will retry automatically.");await refresh();}catch(error){setMessage(`Restore stopped before replacement: ${safeError(error)}`);}}
 async function signOut(){await client?.auth.signOut();coordinator.current?.dispose();clearAccountSync();setLinked(false);setHistory([]);setStatus("local-only");setMessage("Signed out. This device’s local workspace remains available.");}
 return <div className="sync-panel account-lounge"><div className="account-hero"><div className="account-avatar">{session?.user.email?.[0]?.toUpperCase()??"A"}</div><div className="grow"><div className="account-kicker">Account &amp; protection</div><div className="account-title">Your work stays local—and can be protected remotely</div><div className="account-copy">Local Vault remains immediate and authoritative for interaction. Signed-in work is copied into immutable server revisions after acknowledgment.</div></div><Tag tone={status==="protected"?"green":status==="conflict"?"red":"neutral"}>{label(status)}</Tag></div>
 {!configured&&<div className="sync-warning"><CloudOff/>Cloud credentials are absent. Account controls are disabled; local autosave and manual JSON recovery remain unchanged.</div>}
 {configured&&!session&&<section className="account-card"><h3>Continue locally or sign in</h3><p className="sub">An account is optional. Signing in never silently replaces this device’s work.</p><div className="sync-grid"><label>Email<input className="field" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input className="field" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label></div><div className="row wrap gap8"><GButton variant="primary" onClick={()=>void auth("signIn")}>Sign in</GButton><GButton onClick={()=>void auth("signUp")}><UserPlus/>Create account</GButton></div></section>}
 {session&&!linked&&<section className="account-card"><h3>Local workspace found</h3><p>This device contains AXOM work. Nothing will be uploaded or replaced until you choose.</p><div className="account-primary-actions"><GButton variant="primary" onClick={()=>void linkLocalWorkspace()}><ShieldCheck/>Use this local workspace with my account</GButton><GButton onClick={()=>void refresh()}><History/>Review account versions first</GButton></div><p className="sub">Starting a blank account workspace is intentionally deferred until a safe account-switching vault boundary is complete.</p></section>}
 {session&&<section className="account-card"><div className="account-section-head"><div><h3>Protected versions</h3><p className="sub">Server acknowledgment is required before AXOM says Protected.</p></div><GButton size="sm" onClick={()=>void refresh()}><RefreshCw/>Refresh</GButton></div>{history.length===0?<p className="sub">No protected versions are visible yet.</p>:<div className="backup-list">{history.map(item=><div className="backup-row" key={item.id}><div><b>{new Date(item.createdAt).toLocaleString()}</b><div className="sub">{item.reason} · schema {item.schemaVersion}</div></div><GButton size="sm" onClick={()=>void restore(item)}>Restore</GButton></div>)}</div>}<GButton size="sm" onClick={()=>void signOut()}><LogOut/>Sign out</GButton></section>}
 <div className="backup-note" role="status"><Cloud/><span>{message}</span></div><p className="sub">Manual JSON export, restore, and merge remain available under Backup &amp; recovery.</p></div>;
}
function label(s:ProtectionStatus){return({"local-only":"LOCAL ONLY","saved-locally":"SAVED LOCALLY",syncing:"SYNCING",protected:"PROTECTED",offline:"OFFLINE — SAVED LOCALLY",retrying:"SYNC ISSUE — RETRYING",conflict:"ACTION REQUIRED"})[s];}function safeError(e:unknown){return e instanceof Error?e.message:"Cloud request failed. Your local work is safe.";}
