import type { NoctyriumState } from "../types";import { deviceId,read,write } from "./syncMetadata";import { snapshotWorkspace } from "./workspaceSnapshot";import type { ProtectionStatus,SnapshotEnvelope,SyncTransport } from "./syncTypes";
export class SyncCoordinator{
  private timer:number|undefined; private running=false; private status:ProtectionStatus="saved-locally"; private listeners=new Set<(s:ProtectionStatus)=>void>();
  constructor(private transport:SyncTransport,private state:()=>NoctyriumState,private delay=3000){}
  subscribe(fn:(s:ProtectionStatus)=>void){this.listeners.add(fn);fn(this.status);return()=>this.listeners.delete(fn);}
  currentStatus(){return this.status;}
  queue(){const meta=read();write({...meta,pending:true,pendingIdempotencyKey:meta.pendingIdempotencyKey??crypto.randomUUID()});this.set(navigator.onLine?"saved-locally":"offline");if(this.timer)clearTimeout(this.timer);this.timer=window.setTimeout(()=>void this.flush(),this.delay);}
  async flush(reason:SnapshotEnvelope["reason"]="automatic"){if(this.running)return;const meta=read();if(!meta.pending&&reason==="automatic")return;if(!navigator.onLine){this.set("offline");return;}this.running=true;this.set("syncing");try{const envelope=await snapshotWorkspace(this.state(),{deviceId:deviceId(),baseRevision:meta.baseRevision,idempotencyKey:meta.pendingIdempotencyKey,reason});const result=await this.transport.push(envelope);if(result.status==="conflict"){write({...read(),pending:false,pendingIdempotencyKey:undefined,attempt:0});this.set("conflict");return;}write({...read(),baseRevision:result.revision,pending:false,pendingIdempotencyKey:undefined,lastHash:envelope.contentHash,lastProtectedAt:new Date().toISOString(),attempt:0});this.set("protected");}catch{const current=read();write({...current,pending:true,attempt:Math.min(current.attempt+1,6)});this.set("retrying");const backoff=Math.min(60000,1000*2**current.attempt);this.timer=window.setTimeout(()=>void this.flush(),backoff);}finally{this.running=false;}}
  reconnect=()=>{if(read().pending)void this.flush();}; dispose(){if(this.timer)clearTimeout(this.timer);this.listeners.clear();} private set(s:ProtectionStatus){this.status=s;this.listeners.forEach(fn=>fn(s));}
}
